### ISSUE TITLE
Does not work with newer Python version

### ISSUE THREAD

**Issue by AsciiWolf** [stethewwolf/gResistor#1]
When trying to [update](https://github.com/flathub/eu.stethewwolf.gresistor/pull/1) the gResistor Flatpak runtime, gResistor [no longer runs](https://github.com/flathub/eu.stethewwolf.gresistor/pull/1#issuecomment-1642768007) on the new build (using Python 3.10.12). This gets printed on stdout:

```
Traceback (most recent call last):
  File "/app/bin/gresistor3", line 33, in <module>
    sys.exit(load_entry_point('gResistor==3.2.5', 'console_scripts', 'gresistor3')())
  File "/app/bin/gresistor3", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gResistor
```

**Comment by stethewwolf** [comment]
Hello, I made some fix on this repo and opened a new brach https://github.com/flathub/eu.stethewwolf.gresistor/tree/gtk_runtime_44
